# Generated by Django 6.0.4 on 2026-05-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
